version: "3.7"

services:
  api:
    build:
      context: .
    volumes:
      - .:/code
    command: local
    env_file:
      - ././server/.env
    ports:
      - "8000:8000"
    networks:
      - public
      - private

networks:
  public:
  private:
